export enum USER_ROLE {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum ORDER_STATUS {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELED = 'CANCELED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
}



export enum PAYMENT_METHODS {
  CASH = 'CASH',
  VNPAY = 'VNPAY',
}
