import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'sonner';
import ThemeProvider from '@/providers/theme-provider';
import AuthProvider from '@/providers/AuthProvider';
import { fontVariables } from '@/config/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontVariables} antialiased font-sans min-h-screen bg-background text-foreground`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {children}
            <Toaster
              richColors
              position="top-right"
              expand={false}
              visibleToasts={4}
            />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
