import type { Metadata } from 'next';
import '../globals.css';
import { Toaster } from 'sonner';
import ThemeProvider from '@/providers/theme-provider';
import AuthProvider from '@/providers/AuthProvider';
import { fontVariables } from '@/config/fonts';
import { NextIntlClientProvider } from "next-intl";
import { getMessages, getRequestConfig, setRequestLocale } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { locale } = await params;
  setRequestLocale(locale);
  const messages = await getMessages();


  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${fontVariables} antialiased font-sans min-h-screen bg-background text-foreground`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider locale={locale} messages={messages}>

            <AuthProvider>
              {children}
              <Toaster
                richColors
                position="top-right"
                expand={false}
                visibleToasts={4}
              />
            </AuthProvider>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
